### PR TITLE
input-field: dots improvements

### PR DESCRIPTION
**Pull request by bvr-yr**
- bring back fade
- animate overflow

https://github.com/hyprwm/hyprlock/assets/130279855/d1146760-a8fc-4b71-9ec4-318f0c125299

### CODE REVIEW

**Comment by vaxerski** [comment]
off-center:

image

flashes and jitters on the left:

https://github.com/hyprwm/hyprlock/assets/43317083/03bfad42-8049-4c8a-8a5b-2258886ff49a

**Comment by bvr-yr** [comment]
it is now always center-aligned when overflown, or should i force left/right padding alignment when `dots_center = false`?

**Comment by vaxerski** [comment]
center on overflow is ok

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
