### PR TITLE
Added the option to daemonize the process

### PR DESCRIPTION
**Pull request by stojanov**
Added the option for the process to be forked when starting.

Why would this be useful ?
I tried running hyprlock from wlogout and then suspending the system, but that didn't work since the system would first lock and then when unlocking would suspend, this should solve that problem

### CODE REVIEW

**Comment by vaxerski** [comment]
what

**Comment by stojanov** [comment]
Ahh sorry, misstyped, after doing `hyprlock && systemctl suspend` what would happen is first the system would lock and after that unlocking/exiting hyprlock the system woud suspend immediately. This is gust forking the process and letting the suspend command run

**Comment by vaxerski** [comment]
what's the point? Just run `hyprlock & systemctl suspend`?

**Comment by stojanov** [comment]
Well, in a sense, yes. I'm not sure what else this will be useful in. I'm not sure if this also aligns with the idea of hyprlock.

**Comment by stojanov** [comment]
Ahh i see, that is also useful. Sorry for my useless implementation

**Pull request closed without merging**
