### PR TITLE
widgets: add Shape + minor image improve

### LINKED ISSUE #253: [REQ] Add custom shape
Some users (aka me, nobody cares) may want to fill a custom rectangle as background of labels, input, whatever, to better distinguish them from the all other stuff. At the moment this can be done with an image (like picture below), but this has disadvantages:
- You need a .png picture of solid color, want to change it - go to gimp, ugh
- Picture must be with specific ratio, same as above

2024-04-01T12:00:06,417336041+04:00

It would be easier, if there will be a widget, that just fill rectangle of custom shape with specified color, that also has border, shadow and all eye candy stuff. Also it must lay behind other widgets - images, labels etc. Basically something like this:

```
shape (or a rectangle, box, doesn't matter how it called) {
    monitor =
    color = rgba(14881337) # background color
    size = 228, 228 # x, y
    rounding = 69 # negative values mean circle
    border_size = 1
    border_color = rgb(696969)
    rotate = 0 # degrees, counter-clockwise

    # All shadow stuff ...

    position = 0, 0
    halign = center
    valign = center
}
```

### PR DESCRIPTION
**Pull request by bvr-yr**
that's to close #253

nothing special, except xray

well, despite it's stupid to punch a hole in background, someone may find it useful

I've been messaged to share a config from #247 video for cava bars, and I think updating labels every 33 ms is much more stupid :D

anyways, it is a harmless option after all

https://github.com/hyprwm/hyprlock/assets/130279855/53ef3f14-563d-4b75-bd28-23c0a85e246b

dunno, looks ok

also added some minor stuff to Image

### CODE REVIEW

**Comment by Ligthiago** [comment]
Nice. 
But I encounter a bug: if the  height of shape smaller or equal to width (size = 400, 300 for example) and shape is rotated - I get weird artifact or borders, see picture. Optionally you have to set a big `rounding` to see a bug better

Similar to this has been on images before get fixed.

2024-04-09T16:32:12,661813850+04:00

**Comment by bvr-yr** [comment]
aye just wanted to ask vaxry if I need to glClear here too, will add

**Comment by vaxerski** [comment]
я тоже понял

**Review by vaxerski — APPROVED** [review]
lgtm
wiki mr pls

also where is the backdoor

**Comment by bvr-yr** [comment]
maybe create FB no matter rotated or not? honestly looks a bit ugly on fade-in/fade-out when borderBox is bright and shape is dark

**Review by vaxerski — APPROVED** [review]
yah

**Pull request merged**
