### PR TITLE
add libdrm dependency in README

### PR DESCRIPTION
**Pull request by alba4k**
https://github.com/hyprwm/hyprlock/commit/29c5d4da94a26ba6a6491c24de113ee9c0a2b29c

Should this be added in the README too?

and yeah, probably also in the aur pkgbuild

### CODE REVIEW

**Comment by vaxerski** [comment]
gbm too

**Comment by alba4k** [comment]
Isnt that included in mesa?

**Comment by vaxerski** [comment]
it is but mesa is not listed in the deps either

**Comment by alba4k** [comment]
`git push -f` just became my favorite command

> but mesa is not listed
it is now I guess

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
