### PR TITLE
Added BMP image handling, the same as in hyprpaper

### PR DESCRIPTION
**Pull request by barrrguzin**
Copy this https://github.com/hyprwm/hyprpaper/pull/175 to hyprlock

### CODE REVIEW

**Comment by vaxerski** [comment]
generally I want to migrate this and the async resource gatherer to a separate library in the future

**Comment by PaideiaDilemma** [comment]
> generally I want to migrate this and the async resource gatherer to a separate library in the future

Let me know if we can help with that :)

**Comment by vaxerski** [comment]
I'll do it after 0.42 and when I have some time... possibly in september, I need to cleanup the ecosystem once all the turmoil is over

**Comment by alba4k** [comment]
@vaxerski can't this be closed now? or moved to https://github.com/hyprwm/hyprgraphics

**Comment by vaxerski** [comment]
yes

**Pull request closed without merging**
