### PR TITLE
nix: various improvments to the hm module

### PR DESCRIPTION
**Pull request by Gerg-L**
Leaving this here as a draft for now...
the config file is now automagically generated 
along with a few other fixes... might try to make a smarter way to make all the options because there's so many
first 3 commits should be no-ops
4th is just running `nix fmt`
5th is a temporary commit while I ensure the config file generation is correct.
will pick this up sometime tomorrow most likely

### CODE REVIEW

**Comment by NotAShelf** [comment]
👎🏻 for nixfmt, it sucks

**Comment by Gerg-L** [comment]
> 👎🏻 for nixfmt, it sucks

I didn't run nixfmt, I ran nix fmt.

Which is Alejandra...

**Comment by NotAShelf** [comment]
Ah right, diff looked weird to me. Probably someone used something else beforehand?

**Comment by Gerg-L** [comment]
The original looks manually formatted to me

**Comment by Gerg-L** [comment]
Haven't tested extensively but looks good to me.
Any thoughts?

**Comment by Gerg-L** [comment]
ok it's still broken for some reason wtf

**Review by fufexan — APPROVED** [review]
Looks good generally, but soon this module (and hypridle's) will be obsoleted by
- https://github.com/nix-community/home-manager/pull/5324
- https://github.com/nix-community/home-manager/pull/5325
- https://github.com/nix-community/home-manager/pull/5341

**Comment by Gerg-L** [comment]
> Looks good generally, but soon this module (and hypridle's) will be obsoleted by
> ...

kinda nuts changes there
this PR doesn't really matter then...

**Comment by Gerg-L** [comment]
was fun to work on, is pointless D:

**Pull request closed without merging**
