### PR TITLE
input-field: add capslock and numlock options

### PR DESCRIPTION
**Pull request by bvr-yr**
- `capslock_color`
- `numlock_color`
- `invert_numlock` change color when numlock off (for those who rely on numpad, like me)
- `bothlock_color` when both conditions

by default `color` options are `-1`, which means ignore state
that's ok? or maybe add default colors but leave ability to set `-1`
i don't know how to handle this correctly in Home Manager, as not on Nix
should i just use
```nix
capslock_color = ${toString background.capslock_color}
```
and which type to set then?

now function looks way more cleanly and other stuff can be added easier

### CODE REVIEW

**Comment by bvr-yr** [comment]
can you test a bit on multi-monitor? there been some issues with colors not being updated properly to the end on one of monitors, i think i fixed that but still kinda laggy a bit rarely with > 300ms transition, perhaps just my gpu sucks here

**Review by vaxerski — APPROVED** [review]
lgtm

**Comment by vaxerski** [comment]
for nix @fufexan

**Comment by fufexan** [comment]
@bvr-yr added the nix options. If you feel the descriptions don't match well, feel free to change them.

**Comment by bvr-yr** [comment]
nah that's good, thanks!

**Review by vaxerski — APPROVED** [review]
g

**Pull request merged**
