### PR TITLE
Make Ctrl+u clear password input

### PR DESCRIPTION
**Pull request by noahgitsham**
Fixes https://github.com/hyprwm/hyprlock/issues/222

### CODE REVIEW

**Comment by noahgitsham** [comment]
Lmk if you also want Ctrl+Backspace to clear input

**Comment by vaxerski** [comment]
> Lmk if you also want Ctrl+Backspace to clear input

that aint a bad idea.

**Comment by noahgitsham** [comment]
Had to reorder if statements (which should be fine?), but should be implemented

**Review by vaxerski — APPROVED** [review]
sure

**Pull request merged**
