### PR TITLE
 hold backspace to delete text entered #263

### PR DESCRIPTION
**Pull request by kojq**
scuffed. need to fix.

### CODE REVIEW

**Comment by PaideiaDilemma** [comment]
I also drafted this one up.
You may look at it here: https://github.com/PaideiaDilemma/hyprlock/tree/hold-backspace

**Comment by kojq** [comment]
I dunno how the generalized one would be used aside from when both entering and deleting text, but I like it.

Check if the repeatable rate is not too fast or slow (or could be configured). Other than that, I will close this when yours merges.

**Comment by PaideiaDilemma** [comment]
> I dunno how the generalized one would be used aside from when both entering and deleting text, but I like it.

Honestly idk either, but it made more sense to me doing it like that.

**Comment by kojq** [comment]
Closing as #277 is in good condition.

**Pull request closed without merging**
